/**
 * Syncs the fixed system prompts from /system_prompts into a TypeScript
 * module (`functions/api/prompts.gen.ts`) that the Cloudflare edge function
 * can import at bundle time. Cloudflare Pages Functions cannot read files
 * from disk at runtime, so the .md files are compiled in via this script.
 *
 * Run automatically via `predev` / `prebuild` (see package.json).
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const readPrompt = (name) =>
  readFileSync(join(root, "system_prompts", name), "utf8");

/**
 * The .md files ship with a static example <system-reminder> block (date etc).
 * The edge function injects a fresh one at request time, so strip the
 * placeholder from the compiled prompt.
 */
const stripStaticReminders = (text) =>
  text.replace(/<system-reminder>[\s\S]*?<\/system-reminder>/g, "").trim();

const escapeTemplateLiteral = (text) =>
  text.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

const base = stripStaticReminders(readPrompt("askinglucidly.md"));
const deepResearch = stripStaticReminders(readPrompt("deep-research.md"));

const output = `// AUTO-GENERATED by scripts/sync-prompts.mjs — DO NOT EDIT BY HAND.
// Source of truth: /system_prompts/*.md
// Regenerate with: npm run sync-prompts

export const BASE_SYSTEM_PROMPT = \`${escapeTemplateLiteral(base)}\`;

export const DEEP_RESEARCH_SYSTEM_PROMPT = \`${escapeTemplateLiteral(deepResearch)}\`;
`;

const target = join(root, "functions", "api", "prompts.gen.ts");
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, output, "utf8");

console.log(`[sync-prompts] Wrote ${target}`);
console.log(
  `[sync-prompts] base prompt: ${base.length} chars, deep research prompt: ${deepResearch.length} chars`,
);
